function test
%TEST test xmlparse and xmlwrite.

% Generate the xml file.
xml1 = ['<?xml version="1.0"?>'            char(10) ...
    '<note>'                               char(10) ...
    '    <to>Bob</to>'                     char(10) ...
    '    <from>Sally</from>'               char(10) ...
    '    <heading>Hey there</heading>'     char(10) ...
    '    <body>Yo, yo! What''s up?</body>' char(10) ...
    '</note>'                              char(10) ...
    '<note>'                               char(10) ...
    '    <to>Kendra</to>'                  char(10) ...
    '    <from>Dan</from>'                 char(10) ...
    '    <heading>My feelings</heading>'   char(10) ...
    '    <body>Foo bar.</body>'            char(10) ...
    '</note>'                              char(10)...
    ''];

% Write the xml to file.
fid = fopen('example1.xml','w');
fprintf(fid,xml1);

% Show what the resulting struct should look like.
a.note(1) = struct('to','Bob','from','Sally','heading','Hey there',...
    'body','Yo, yo! What''s up?');
a.note(2) = struct('to','Kendra','from','Dan','heading','My feelings',...
    'body','Foo bar.');

b = xmlparse('example1.xml');
xml2 = xmlwrite(a,'example2.xml');

% Check it all out.
t1 = struct2array(struct2array(a));
t2 = struct2array(struct2array(a));
[s,val] = system('diff example1.xml example2.xml');

% Do the tests.
assert(strcmp(t1,t2)    ,'xmlparse has failed.');
assert(isempty(val),'xmlwrite has failed');
assert(strcmp(xml1,xml2),'xmlwrite has failed');

end